# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleBallAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red1', models.IntegerField()),
                ('red2', models.IntegerField()),
                ('red3', models.IntegerField()),
                ('red4', models.IntegerField()),
                ('red5', models.IntegerField()),
                ('red6', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': '\u5168\u90e8\u6570\u636e',
                'verbose_name_plural': '\u5168\u90e8\u6570\u636e',
            },
        ),
    ]
