# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myssq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doubleballall',
            table='doubleball_all',
        ),
    ]
