# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myssq', '0002_auto_20180602_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleballall',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
